# Generated by Django 5.2.12 on 2026-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_age_user_can_be_contacted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
